/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_apps.View.Welcome;

import crud_apps.View.Welcome.*;
import crud_apps.Controller.CustomFonts;
import crud_apps.Controller.Lokasi;

/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class MainHomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    CustomFonts fontCustoms = new CustomFonts();
    Lokasi lokasi = new Lokasi(this);
    WelcomeFrameLogin login = new WelcomeFrameLogin();
    public MainHomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        CustomersPanel = new javax.swing.JPanel();
        AddNewCustomer = new crud_apps.Controller.CustomButton();
        EditCustomer = new crud_apps.Controller.CustomButton();
        ListOfCustomers = new crud_apps.Controller.CustomButton();
        DeleteCustomer = new crud_apps.Controller.CustomButton();
        BgWhiteUsersPanel = new javax.swing.JLabel();
        ProductionPanel = new javax.swing.JPanel();
        AddNewProduct = new crud_apps.Controller.CustomButton();
        EditProduct = new crud_apps.Controller.CustomButton();
        ListOfProduct = new crud_apps.Controller.CustomButton();
        DeleteProduct = new crud_apps.Controller.CustomButton();
        BgWhiteProductionPanel = new javax.swing.JLabel();
        TransactiosPanel = new javax.swing.JPanel();
        AddNewTransaction = new crud_apps.Controller.CustomButton();
        ActiveTransaction = new crud_apps.Controller.CustomButton();
        BgWhiteProductionPanel1 = new javax.swing.JLabel();
        ReportsPanel = new javax.swing.JPanel();
        MonthlyReport = new crud_apps.Controller.CustomButton();
        DailyReport = new crud_apps.Controller.CustomButton();
        BgWhiteProductionPanel2 = new javax.swing.JLabel();
        LogOut = new crud_apps.Controller.CustomButton();
        BackgroundLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        Start = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        menutTitle = new javax.swing.JMenu();
        XBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 670));
        setName("frame0"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.setMinimumSize(new java.awt.Dimension(1020, 670));
        panelBg.setPreferredSize(new java.awt.Dimension(1020, 670));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 4, true), "Customer's Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        CustomersPanel.setOpaque(false);
        CustomersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddNewCustomer.setText("Add new a Customer");
        AddNewCustomer.setTepi(20);
        CustomersPanel.add(AddNewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 40));

        EditCustomer.setText("Edit a Customer");
        EditCustomer.setTepi(20);
        CustomersPanel.add(EditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        ListOfCustomers.setText("List of Customers");
        ListOfCustomers.setTepi(20);
        CustomersPanel.add(ListOfCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 40));

        DeleteCustomer.setText("Delete Customer");
        DeleteCustomer.setTepi(20);
        CustomersPanel.add(DeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 40));

        BgWhiteUsersPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        CustomersPanel.add(BgWhiteUsersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 330));

        panelBg.add(CustomersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 270, 360));

        ProductionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 4, true), "Production's Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        ProductionPanel.setOpaque(false);
        ProductionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddNewProduct.setText("Add new a Product");
        AddNewProduct.setTepi(20);
        ProductionPanel.add(AddNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 40));

        EditProduct.setText("Edit a Product");
        EditProduct.setTepi(20);
        ProductionPanel.add(EditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        ListOfProduct.setText("List of Product");
        ListOfProduct.setTepi(20);
        ProductionPanel.add(ListOfProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 40));

        DeleteProduct.setText("Delete Product");
        DeleteProduct.setTepi(20);
        ProductionPanel.add(DeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 40));

        BgWhiteProductionPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        ProductionPanel.add(BgWhiteProductionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 330));

        panelBg.add(ProductionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 270, 360));

        TransactiosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 4, true), "Transactions's Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        TransactiosPanel.setOpaque(false);
        TransactiosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddNewTransaction.setText("Add new Transaction");
        AddNewTransaction.setTepi(20);
        TransactiosPanel.add(AddNewTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 40));

        ActiveTransaction.setText("Active Transaction");
        ActiveTransaction.setTepi(20);
        TransactiosPanel.add(ActiveTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        BgWhiteProductionPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        TransactiosPanel.add(BgWhiteProductionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 180));

        panelBg.add(TransactiosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 270, 210));

        ReportsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 4, true), "Report's Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        ReportsPanel.setOpaque(false);
        ReportsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MonthlyReport.setText("Monthly Report");
        MonthlyReport.setTepi(20);
        ReportsPanel.add(MonthlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 40));

        DailyReport.setText("Daily Report");
        DailyReport.setTepi(20);
        ReportsPanel.add(DailyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        BgWhiteProductionPanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        ReportsPanel.add(BgWhiteProductionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 180));

        panelBg.add(ReportsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 270, 210));

        LogOut.setText("Log Out");
        LogOut.setTepi(20);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        panelBg.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 90, 40));

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BackgroundWellcome1.png"))); // NOI18N
        panelBg.add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 670));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);
        menuBar.setFont(fontCustoms.getRobotoMedium().deriveFont(20f)
        );
        menuBar.setMaximumSize(new java.awt.Dimension(1020, 50));
        menuBar.setOpaque(false);
        menuBar.setPreferredSize(new java.awt.Dimension(1020, 30));

        menuFile.setBorder(null);
        menuFile.setText("File");
        menuFile.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        loginMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        loginMenu.setText("Login");
        loginMenu.setBorder(null);
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        menuFile.add(loginMenu);

        Start.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        Start.setText("Start");
        Start.setBorder(null);
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        menuFile.add(Start);

        menuBar.add(menuFile);

        menuHelp.setBorder(null);
        menuHelp.setText("Help");
        menuHelp.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        helpMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        helpMenu.setText("Help");
        helpMenu.setBorder(null);
        menuHelp.add(helpMenu);

        aboutMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        aboutMenu.setText("About");
        aboutMenu.setBorder(null);
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        menuHelp.add(aboutMenu);

        menuBar.add(menuHelp);

        menutTitle.setText(getTitle());
        menutTitle.setContentAreaFilled(false);
        menutTitle.setEnabled(false);
        menutTitle.setFont(fontCustoms.getRobotoMedium().deriveFont(14f));
        menutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menutTitle.setIconTextGap(400);
        menutTitle.setMaximumSize(new java.awt.Dimension(1000, 50));
        menutTitle.setPreferredSize(new java.awt.Dimension(880, 24));
        menutTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menutTitleMouseDragged(evt);
            }
        });
        menutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menutTitleMousePressed(evt);
            }
        });
        menuBar.add(menutTitle);
        menutTitle.getAccessibleContext().setAccessibleName("Main Home");

        XBtn.setBorder(null);
        XBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/button-x.png"))); // NOI18N
        XBtn.setContentAreaFilled(false);
        XBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });
        menuBar.add(XBtn);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBtnMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void menutTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMousePressed
        // TODO add your handling code here:
        lokasi.pressed(evt);
    }//GEN-LAST:event_menutTitleMousePressed

    private void menutTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMouseDragged
        // TODO add your handling code here:
        lokasi.dragged(evt);
    }//GEN-LAST:event_menutTitleMouseDragged

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginMenuActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        new WelcomeFrameStart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private crud_apps.Controller.CustomButton ActiveTransaction;
    private crud_apps.Controller.CustomButton AddNewCustomer;
    private crud_apps.Controller.CustomButton AddNewProduct;
    private crud_apps.Controller.CustomButton AddNewTransaction;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JLabel BgWhiteProductionPanel;
    private javax.swing.JLabel BgWhiteProductionPanel1;
    private javax.swing.JLabel BgWhiteProductionPanel2;
    private javax.swing.JLabel BgWhiteUsersPanel;
    private javax.swing.JPanel CustomersPanel;
    private crud_apps.Controller.CustomButton DailyReport;
    private crud_apps.Controller.CustomButton DeleteCustomer;
    private crud_apps.Controller.CustomButton DeleteProduct;
    private crud_apps.Controller.CustomButton EditCustomer;
    private crud_apps.Controller.CustomButton EditProduct;
    private crud_apps.Controller.CustomButton ListOfCustomers;
    private crud_apps.Controller.CustomButton ListOfProduct;
    private crud_apps.Controller.CustomButton LogOut;
    private crud_apps.Controller.CustomButton MonthlyReport;
    private javax.swing.JPanel ProductionPanel;
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JMenuItem Start;
    private javax.swing.JPanel TransactiosPanel;
    private javax.swing.JMenu XBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menutTitle;
    private javax.swing.JPanel panelBg;
    // End of variables declaration//GEN-END:variables
}
