/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_apps.View.Welcome;

import crud_apps.Controller.CustomFonts;
import crud_apps.Controller.Lokasi;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class WelcomeFrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    Lokasi lokasi = new Lokasi(this);
    private boolean over;
    CustomFonts fontCustoms = new CustomFonts();
    public WelcomeFrameRegister() {
        initComponents();
    }
    
//    public void itemStateChanged

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        panelRegisterForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelFullName = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        bgfullname = new crud_apps.Controller.CustomButton();
        panelUsername = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernameTxtRegist = new javax.swing.JTextField();
        bgUsernameRegist = new crud_apps.Controller.CustomButton();
        panelEmail = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        bgEmail = new crud_apps.Controller.CustomButton();
        panelPasswordReg = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        passwordReg = new javax.swing.JPasswordField();
        bgPassword = new crud_apps.Controller.CustomButton();
        panelPasswordConfirm = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        passwordConfirm = new javax.swing.JPasswordField();
        bgPasswordConfirm = new crud_apps.Controller.CustomButton();
        readPrivasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ceklis = new javax.swing.JCheckBox();
        RegistrationBtn = new crud_apps.Controller.CustomButton();
        bgWhite = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        startMenu = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        menutTitle = new javax.swing.JMenu();
        XBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 670));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.setMinimumSize(new java.awt.Dimension(1020, 670));
        panelBg.setPreferredSize(new java.awt.Dimension(1020, 670));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegisterForm.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "Registration Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 255, 255))); // NOI18N
        panelRegisterForm.setOpaque(false);
        panelRegisterForm.setPreferredSize(new java.awt.Dimension(1020, 650));
        panelRegisterForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(fontCustoms.getHandleeRegular().deriveFont(28f)
        );
        jLabel1.setText("Preapare your Journey form here !");
        panelRegisterForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        panelFullName.setOpaque(false);
        panelFullName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel5.setText("Full Name");
        panelFullName.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        fullNameTxt.setFont(fontCustoms.getPoppinsMedium().deriveFont(18f)
        );
        fullNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullNameTxt.setText("Type your Full name here");
        fullNameTxt.setToolTipText("Type your Full name here");
        fullNameTxt.setBorder(null);
        fullNameTxt.setFocusable(false);
        fullNameTxt.setName("Type your Full name here"); // NOI18N
        fullNameTxt.setNextFocusableComponent(usernameTxtRegist);
        fullNameTxt.setOpaque(false);
        fullNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullNameTxtFocusGained(evt);
            }
        });
        fullNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullNameTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullNameTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fullNameTxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fullNameTxtMouseReleased(evt);
            }
        });
        panelFullName.add(fullNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));
        fullNameTxt.getAccessibleContext().setAccessibleName("Type your Full name here");

        bgfullname.setBackground(new java.awt.Color(255, 255, 255));
        bgfullname.setBorder(null);
        bgfullname.setEnabled(false);
        bgfullname.setTepi(25);
        bgfullname.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgfullname.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgfullname.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelFullName.add(bgfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 300, 150));

        panelUsername.setOpaque(false);
        panelUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel6.setText("Username");
        panelUsername.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        usernameTxtRegist.setFont(fontCustoms.getPoppinsMedium().deriveFont(18f)
        );
        usernameTxtRegist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTxtRegist.setText("Create your username");
        usernameTxtRegist.setToolTipText("Create your username");
        usernameTxtRegist.setBorder(null);
        usernameTxtRegist.setFocusable(false);
        usernameTxtRegist.setNextFocusableComponent(emailTxt);
        usernameTxtRegist.setOpaque(false);
        usernameTxtRegist.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtRegistFocusGained(evt);
            }
        });
        usernameTxtRegist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernameTxtRegistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameTxtRegistMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameTxtRegistMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usernameTxtRegistMouseReleased(evt);
            }
        });
        panelUsername.add(usernameTxtRegist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));
        usernameTxtRegist.getAccessibleContext().setAccessibleName("Type your Full name here");

        bgUsernameRegist.setBackground(new java.awt.Color(255, 255, 255));
        bgUsernameRegist.setBorder(null);
        bgUsernameRegist.setEnabled(false);
        bgUsernameRegist.setTepi(25);
        bgUsernameRegist.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgUsernameRegist.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgUsernameRegist.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelUsername.add(bgUsernameRegist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 300, 150));

        panelEmail.setOpaque(false);
        panelEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel7.setText("Email");
        panelEmail.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        emailTxt.setFont(fontCustoms.getPoppinsMedium().deriveFont(18f)
        );
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTxt.setText("Type your email here");
        emailTxt.setToolTipText("Type your email here");
        emailTxt.setBorder(null);
        emailTxt.setFocusable(false);
        emailTxt.setNextFocusableComponent(passwordReg);
        emailTxt.setOpaque(false);
        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFocusGained(evt);
            }
        });
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailTxtMouseReleased(evt);
            }
        });
        panelEmail.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgEmail.setBackground(new java.awt.Color(255, 255, 255));
        bgEmail.setBorder(null);
        bgEmail.setEnabled(false);
        bgEmail.setTepi(25);
        bgEmail.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgEmail.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgEmail.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelEmail.add(bgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 300, 150));

        panelPasswordReg.setOpaque(false);
        panelPasswordReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel8.setText("Password");
        panelPasswordReg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        passwordReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordReg.setText("password");
        passwordReg.setToolTipText("password");
        passwordReg.setBorder(null);
        passwordReg.setEchoChar('\u0000');
        passwordReg.setFocusable(false);
        passwordReg.setNextFocusableComponent(passwordConfirm);
        passwordReg.setOpaque(false);
        passwordReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegFocusGained(evt);
            }
        });
        passwordReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordRegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordRegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordRegMouseReleased(evt);
            }
        });
        panelPasswordReg.add(passwordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgPassword.setBackground(new java.awt.Color(255, 255, 255));
        bgPassword.setBorder(null);
        bgPassword.setEnabled(false);
        bgPassword.setTepi(25);
        bgPassword.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgPassword.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgPassword.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelPasswordReg.add(bgPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelPasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 300, 150));

        panelPasswordConfirm.setOpaque(false);
        panelPasswordConfirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel9.setText("Confirmation Password");
        panelPasswordConfirm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        passwordConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordConfirm.setText("password");
        passwordConfirm.setToolTipText("password");
        passwordConfirm.setBorder(null);
        passwordConfirm.setEchoChar('\u0000');
        passwordConfirm.setFocusable(false);
        passwordConfirm.setNextFocusableComponent(ceklis);
        passwordConfirm.setOpaque(false);
        passwordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordConfirmFocusGained(evt);
            }
        });
        passwordConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordConfirmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseReleased(evt);
            }
        });
        passwordConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordConfirmKeyReleased(evt);
            }
        });
        panelPasswordConfirm.add(passwordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgPasswordConfirm.setBackground(new java.awt.Color(255, 255, 255));
        bgPasswordConfirm.setBorder(null);
        bgPasswordConfirm.setEnabled(false);
        bgPasswordConfirm.setTepi(25);
        bgPasswordConfirm.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgPasswordConfirm.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgPasswordConfirm.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelPasswordConfirm.add(bgPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 300, 150));

        readPrivasi.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(12f)
        );
        readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
        readPrivasi.setText("read Privacy and Policy");
        readPrivasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                readPrivasiFocusGained(evt);
            }
        });
        readPrivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readPrivasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readPrivasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readPrivasiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                readPrivasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                readPrivasiMouseReleased(evt);
            }
        });
        readPrivasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readPrivasiKeyPressed(evt);
            }
        });
        panelRegisterForm.add(readPrivasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));
        panelRegisterForm.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 240, 10));

        ceklis.setText("I accept Privacy and Policy");
        ceklis.setNextFocusableComponent(RegistrationBtn);
        ceklis.setOpaque(false);
        ceklis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ceklisItemStateChanged(evt);
            }
        });
        ceklis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ceklisKeyPressed(evt);
            }
        });
        panelRegisterForm.add(ceklis, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        RegistrationBtn.setBackground(new java.awt.Color(255, 255, 255));
        RegistrationBtn.setBorder(null);
        RegistrationBtn.setText("Create your an Account !");
        RegistrationBtn.setEnabled(false);
        RegistrationBtn.setFont(fontCustoms.getRobotoBlak().deriveFont(14f)
        );
        RegistrationBtn.setTepi(25);
        RegistrationBtn.setWarnaClick(new java.awt.Color(255, 255, 0));
        RegistrationBtn.setWarnaOver(new java.awt.Color(255, 153, 51));
        RegistrationBtn.setWarnaTepi(new java.awt.Color(255, 153, 51));
        RegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationBtnActionPerformed(evt);
            }
        });
        panelRegisterForm.add(RegistrationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 200, 50));

        bgWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        panelRegisterForm.add(bgWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panelBg.add(panelRegisterForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BackgroundWellcome1.png"))); // NOI18N
        panelBg.add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);
        menuBar.setFont(fontCustoms.getRobotoMedium().deriveFont(20f)
        );
        menuBar.setMaximumSize(new java.awt.Dimension(1020, 50));
        menuBar.setOpaque(false);
        menuBar.setPreferredSize(new java.awt.Dimension(1020, 30));

        menuFile.setBorder(null);
        menuFile.setText("File");
        menuFile.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        startMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        startMenu.setText("Start");
        startMenu.setBorder(null);
        startMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMenuActionPerformed(evt);
            }
        });
        menuFile.add(startMenu);

        loginMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        loginMenu.setText("Login");
        loginMenu.setBorder(null);
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        menuFile.add(loginMenu);

        menuBar.add(menuFile);

        menuHelp.setBorder(null);
        menuHelp.setText("Help");
        menuHelp.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        helpMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        helpMenu.setText("Help");
        helpMenu.setBorder(null);
        menuHelp.add(helpMenu);

        aboutMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        aboutMenu.setText("About");
        aboutMenu.setBorder(null);
        menuHelp.add(aboutMenu);

        menuBar.add(menuHelp);

        menutTitle.setText(getTitle());
        menutTitle.setContentAreaFilled(false);
        menutTitle.setEnabled(false);
        menutTitle.setFont(fontCustoms.getRobotoMedium().deriveFont(14f));
        menutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menutTitle.setIconTextGap(400);
        menutTitle.setMaximumSize(new java.awt.Dimension(1000, 50));
        menutTitle.setPreferredSize(new java.awt.Dimension(880, 24));
        menutTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menutTitleMouseDragged(evt);
            }
        });
        menutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menutTitleMousePressed(evt);
            }
        });
        menuBar.add(menutTitle);

        XBtn.setBorder(null);
        XBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/button-x.png"))); // NOI18N
        XBtn.setContentAreaFilled(false);
        XBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });
        menuBar.add(XBtn);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBtnMouseClicked

    private void menutTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMousePressed
        // TODO add your handling code here:
        lokasi.pressed(evt);
    }//GEN-LAST:event_menutTitleMousePressed

    private void menutTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMouseDragged
        // TODO add your handling code here:
        lokasi.dragged(evt);
    }//GEN-LAST:event_menutTitleMouseDragged

    private void startMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMenuActionPerformed
        // TODO add your handling code here:
        WelcomeFrameStart start = new WelcomeFrameStart();
        start.setLocation(lokasi.p());
        start.setVisible(true);
        dispose();
    }//GEN-LAST:event_startMenuActionPerformed

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
        WelcomeFrameLogin login = new WelcomeFrameLogin();
        login.setLocation(lokasi.p());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginMenuActionPerformed

    private void fullNameTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameTxtMouseEntered
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarnaOver());
        this.over = true;
        fullNameTxt.setFocusable(over);
    }//GEN-LAST:event_fullNameTxtMouseEntered

    private void fullNameTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameTxtMouseExited
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarna());
        this.over = false;
    }//GEN-LAST:event_fullNameTxtMouseExited

    private void fullNameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameTxtMousePressed
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarnaClick());
        fullNameTxt.selectAll();
    }//GEN-LAST:event_fullNameTxtMousePressed

    private void fullNameTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameTxtMouseReleased
        // TODO add your handling code here:
        if(this.over) {
            bgfullname.setBackground(bgfullname.getWarnaOver());
        } else {
            bgfullname.setBackground(bgfullname.getWarna());
        }
    }//GEN-LAST:event_fullNameTxtMouseReleased

    private void usernameTxtRegistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtRegistMouseEntered
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaOver());
        this.over = true;
        usernameTxtRegist.setFocusable(over);
    }//GEN-LAST:event_usernameTxtRegistMouseEntered

    private void usernameTxtRegistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtRegistMouseExited
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarna());
        this.over = false;
    }//GEN-LAST:event_usernameTxtRegistMouseExited

    private void usernameTxtRegistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtRegistMousePressed
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaClick());
        usernameTxtRegist.selectAll();
    }//GEN-LAST:event_usernameTxtRegistMousePressed

    private void usernameTxtRegistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtRegistMouseReleased
        // TODO add your handling code here:
        if (this.over) {
            bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaOver());
        } else {
            bgUsernameRegist.setBackground(bgUsernameRegist.getWarna());
        }
    }//GEN-LAST:event_usernameTxtRegistMouseReleased

    private void readPrivasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseEntered
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.over = true;
        readPrivasi.setOpaque(over);
//        readPrivasi.setBackground(Color.WHITE);
    }//GEN-LAST:event_readPrivasiMouseEntered

    private void readPrivasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseExited
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.over = false;
        readPrivasi.setOpaque(over);
    }//GEN-LAST:event_readPrivasiMouseExited

    private void readPrivasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMousePressed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readPrivasi.setForeground(Color.WHITE);
        readPrivasi.setOpaque(true);
        
    }//GEN-LAST:event_readPrivasiMousePressed

    private void readPrivasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseReleased
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        if(this.over) {
            readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
            readPrivasi.setOpaque(false);
        } else {
            readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
            readPrivasi.setOpaque(false);
        }
    }//GEN-LAST:event_readPrivasiMouseReleased

    private void passwordRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseEntered
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarnaOver());
        this.over = true;
        passwordReg.setFocusable(over);
    }//GEN-LAST:event_passwordRegMouseEntered

    private void passwordRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseExited
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarna());
        this.over = true;
    }//GEN-LAST:event_passwordRegMouseExited

    private void passwordRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMousePressed
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarnaClick());
        passwordReg.setEchoChar('\u25cf');
    }//GEN-LAST:event_passwordRegMousePressed

    private void passwordRegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseReleased
        // TODO add your handling code here:
        if(this.over){
            bgPassword.setBackground(bgPassword.getWarnaOver());
        } else {
            bgPassword.setBackground(bgPassword.getWarna());
        }
    }//GEN-LAST:event_passwordRegMouseReleased

    private void passwordConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseEntered
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaOver());
        this.over = true;
        passwordConfirm.setFocusable(over);
    }//GEN-LAST:event_passwordConfirmMouseEntered

    private void passwordConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseExited
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarna());
        this.over = false;
    }//GEN-LAST:event_passwordConfirmMouseExited

    private void passwordConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMousePressed
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaClick());
        passwordConfirm.setEchoChar('\u25cf');
    }//GEN-LAST:event_passwordConfirmMousePressed

    private void passwordConfirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseReleased
        // TODO add your handling code here:
        if (this.over){
            bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaOver());
        } else {
            bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarna());
        }
    }//GEN-LAST:event_passwordConfirmMouseReleased

    private void RegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Tombol register clicked");
    }//GEN-LAST:event_RegistrationBtnActionPerformed

    private void ceklisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ceklisItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            RegistrationBtn.setEnabled(true);
        } else {
            RegistrationBtn.setEnabled(false);
        }
    }//GEN-LAST:event_ceklisItemStateChanged

    private void fullNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameTxtFocusGained
        // TODO add your handling code here:
        if (fullNameTxt.getText().equals("Type your Full name here")) {
            fullNameTxt.setText("");
            usernameTxtRegist.setFocusable(true);
        } else if (fullNameTxt.hasFocus()) {
            fullNameTxt.selectAll();
        }
    }//GEN-LAST:event_fullNameTxtFocusGained

    private void usernameTxtRegistFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtRegistFocusGained
        // TODO add your handling code here:
        if (usernameTxtRegist.getText().equals("Create your username")) {
            usernameTxtRegist.setText("");
            emailTxt.setFocusable(true);
        } else if (usernameTxtRegist.hasFocus()) {
            usernameTxtRegist.selectAll();
        }
    }//GEN-LAST:event_usernameTxtRegistFocusGained

    private void passwordRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegFocusGained
        // TODO add your handling code here:
        if (passwordReg.getText().equals("password")) {
            passwordReg.setText("");
            passwordConfirm.setFocusable(true);
            passwordReg.setEchoChar('\u25cf');
        } else if (passwordReg.hasFocus()) {
            passwordReg.selectAll();
        }
    }//GEN-LAST:event_passwordRegFocusGained

    private void passwordConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmFocusGained
        // TODO add your handling code here:
        if (passwordConfirm.getText().equals("password")) {
            passwordConfirm.setText("");
            passwordConfirm.setEchoChar('\u25cf');
        } else if (passwordConfirm.hasFocus()) {
            passwordConfirm.selectAll();
        }
    }//GEN-LAST:event_passwordConfirmFocusGained

    private void emailTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusGained
        // TODO add your handling code here:
        if (emailTxt.getText().equals("Type your email here")) {
            emailTxt.setText("");
            passwordReg.setFocusable(true);
        } else if (emailTxt.hasFocus()) {
            emailTxt.selectAll();
        }
    }//GEN-LAST:event_emailTxtFocusGained

    private void emailTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseEntered
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarnaOver());
        this.over = true;
        emailTxt.setFocusable(over);
    }//GEN-LAST:event_emailTxtMouseEntered

    private void emailTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseExited
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarna());
        this.over = true;
    }//GEN-LAST:event_emailTxtMouseExited

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMousePressed
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarnaClick());
    }//GEN-LAST:event_emailTxtMousePressed

    private void emailTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseReleased
        // TODO add your handling code here:
        if (this.over) {
            bgEmail.setBackground(bgEmail.getWarnaOver());
        } else {
            bgEmail.setBackground(bgEmail.getWarna());
        }
    }//GEN-LAST:event_emailTxtMouseReleased

    private void ceklisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ceklisKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == false) {
            ceklis.setSelected(true);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == true) {
            ceklis.setSelected(false);
        }
    }//GEN-LAST:event_ceklisKeyPressed

    private void passwordConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordConfirmKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == false) {
            int confirmDialog;
            confirmDialog = JOptionPane.showConfirmDialog(null, "Please Accept our Privacy and Policy!"+"\n"+
                    "Click Cancek to read our Privacy and Policy!","EROR",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if ( confirmDialog == JOptionPane.CANCEL_OPTION) {
                passwordConfirm.setNextFocusableComponent(readPrivasi);
                passwordConfirm.nextFocus();
            } else if (confirmDialog == JOptionPane.OK_OPTION) {
                passwordConfirm.setNextFocusableComponent(ceklis);
                passwordConfirm.nextFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == true) {
            RegistrationBtn.doClick();
        }
    }//GEN-LAST:event_passwordConfirmKeyReleased

    private void readPrivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseClicked
        // TODO add your handling code here:
        System.out.println("read it");
    }//GEN-LAST:event_readPrivasiMouseClicked

    private void readPrivasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readPrivasiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("read it");
        }
    }//GEN-LAST:event_readPrivasiKeyPressed

    private void readPrivasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_readPrivasiFocusGained
        // TODO add your handling code here:
        if (readPrivasi.hasFocus()) {
            readPrivasi.setOpaque(true);
            readPrivasi.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_readPrivasiFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private crud_apps.Controller.CustomButton RegistrationBtn;
    private javax.swing.JMenu XBtn;
    private javax.swing.JMenuItem aboutMenu;
    private crud_apps.Controller.CustomButton bgEmail;
    private crud_apps.Controller.CustomButton bgPassword;
    private crud_apps.Controller.CustomButton bgPasswordConfirm;
    private crud_apps.Controller.CustomButton bgUsernameRegist;
    private javax.swing.JLabel bgWhite;
    private crud_apps.Controller.CustomButton bgfullname;
    private javax.swing.JCheckBox ceklis;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menutTitle;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelFullName;
    private javax.swing.JPanel panelPasswordConfirm;
    private javax.swing.JPanel panelPasswordReg;
    private javax.swing.JPanel panelRegisterForm;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPasswordField passwordConfirm;
    private javax.swing.JPasswordField passwordReg;
    private javax.swing.JLabel readPrivasi;
    private javax.swing.JMenuItem startMenu;
    private javax.swing.JTextField usernameTxtRegist;
    // End of variables declaration//GEN-END:variables
}