/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_apps.View.Welcome;

import crud_apps.Controller.CustomFonts;

/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    CustomFonts fontCustoms = new CustomFonts();
    public WelcomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        BackgroundLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        registerMenu = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        menutTitle = new javax.swing.JMenu();
        XBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 670));
        setName("frame0"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.setMinimumSize(new java.awt.Dimension(1020, 670));
        panelBg.setPreferredSize(new java.awt.Dimension(1020, 670));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BackgroundWellcome1.png"))); // NOI18N
        panelBg.add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 670));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);
        menuBar.setFont(fontCustoms.getRobotoMedium().deriveFont(20f)
        );
        menuBar.setMaximumSize(new java.awt.Dimension(1020, 50));
        menuBar.setOpaque(false);
        menuBar.setPreferredSize(new java.awt.Dimension(1020, 30));

        menuFile.setBorder(null);
        menuFile.setText("File");
        menuFile.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        loginMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        loginMenu.setText("Login");
        loginMenu.setBorder(null);
        menuFile.add(loginMenu);

        registerMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        registerMenu.setText("Register");
        registerMenu.setBorder(null);
        menuFile.add(registerMenu);

        menuBar.add(menuFile);

        menuHelp.setBorder(null);
        menuHelp.setText("Help");
        menuHelp.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        helpMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        helpMenu.setText("Help");
        helpMenu.setBorder(null);
        menuHelp.add(helpMenu);

        aboutMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        aboutMenu.setText("About");
        aboutMenu.setBorder(null);
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        menuHelp.add(aboutMenu);

        menuBar.add(menuHelp);

        menutTitle.setText(getTitle());
        menutTitle.setContentAreaFilled(false);
        menutTitle.setEnabled(false);
        menutTitle.setFont(fontCustoms.getRobotoMedium().deriveFont(14f));
        menutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menutTitle.setIconTextGap(400);
        menutTitle.setMaximumSize(new java.awt.Dimension(1000, 50));
        menutTitle.setPreferredSize(new java.awt.Dimension(880, 24));
        menuBar.add(menutTitle);

        XBtn.setBorder(null);
        XBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/button-x.png"))); // NOI18N
        XBtn.setContentAreaFilled(false);
        XBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });
        menuBar.add(XBtn);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JMenu XBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menutTitle;
    private javax.swing.JPanel panelBg;
    private javax.swing.JMenuItem registerMenu;
    // End of variables declaration//GEN-END:variables
}
