/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_apps.View.Welcome;

import crud_apps.Controller.CustomFonts;
import crud_apps.Controller.ForgotPasswordController;
import crud_apps.Controller.Lokasi;
import crud_apps.Model.ForgotPasswordModel;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class WelcomeFrameForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    private ForgotPasswordController forgotPasswordController;
    private ForgotPasswordModel forgotPasswordModel;
    Lokasi lokasi = new Lokasi(this);
    private boolean over;
    CustomFonts fontCustoms = new CustomFonts();
    private WelcomeFrameLogin login = new WelcomeFrameLogin();
    public WelcomeFrameForgotPassword() {
        initComponents();
    }
    
    
//    public void itemStateChanged

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        panelRegisterForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelUsername = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        namaAkunTxt = new javax.swing.JTextField();
        bgfullname = new crud_apps.Controller.CustomButton();
        panelAkunEmail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        akunEmail = new javax.swing.JTextField();
        bgUsernameRegist = new crud_apps.Controller.CustomButton();
        panelEmail = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        bgEmail = new crud_apps.Controller.CustomButton();
        panelPasswordReg = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        passwordReg = new javax.swing.JPasswordField();
        bgPassword = new crud_apps.Controller.CustomButton();
        panelPasswordConfirm = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        passwordConfirm = new javax.swing.JPasswordField();
        bgPasswordConfirm = new crud_apps.Controller.CustomButton();
        readPrivasi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ceklis = new javax.swing.JCheckBox();
        verifyBtn = new crud_apps.Controller.CustomButton();
        cariBtn = new crud_apps.Controller.CustomButton();
        changePasswordBtn = new crud_apps.Controller.CustomButton();
        bgWhite = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        startMenu = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        menutTitle = new javax.swing.JMenu();
        XBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 670));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.setMinimumSize(new java.awt.Dimension(1020, 670));
        panelBg.setPreferredSize(new java.awt.Dimension(1020, 670));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegisterForm.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "Forgot Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 255, 255))); // NOI18N
        panelRegisterForm.setOpaque(false);
        panelRegisterForm.setPreferredSize(new java.awt.Dimension(1020, 650));
        panelRegisterForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(fontCustoms.getHandleeRegular().deriveFont(28f)
        );
        jLabel1.setText("Don't worry we will fix your account");
        panelRegisterForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        panelUsername.setOpaque(false);
        panelUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(14f)
        );
        jLabel10.setText("Type your username");
        panelUsername.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        namaAkunTxt.setFont(fontCustoms.getPoppinsMedium().deriveFont(18f)
        );
        namaAkunTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namaAkunTxt.setText("Type your username");
        namaAkunTxt.setToolTipText("Type your username and hit enter to actice Search Btn");
        namaAkunTxt.setBorder(null);
        namaAkunTxt.setFocusable(false);
        namaAkunTxt.setName("Type your username"); // NOI18N
        namaAkunTxt.setNextFocusableComponent(cariBtn);
        namaAkunTxt.setOpaque(false);
        namaAkunTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaAkunTxtFocusGained(evt);
            }
        });
        namaAkunTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaAkunTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                namaAkunTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namaAkunTxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                namaAkunTxtMouseReleased(evt);
            }
        });
        namaAkunTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaAkunTxtActionPerformed(evt);
            }
        });
        panelUsername.add(namaAkunTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));
        namaAkunTxt.getAccessibleContext().setAccessibleName("Type your username");

        bgfullname.setBackground(new java.awt.Color(255, 255, 255));
        bgfullname.setBorder(null);
        bgfullname.setEnabled(false);
        bgfullname.setTepi(25);
        bgfullname.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgfullname.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgfullname.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelUsername.add(bgfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 300, 150));

        panelAkunEmail.setOpaque(false);
        panelAkunEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel6.setText("Please Make Sure!");
        panelAkunEmail.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        akunEmail.setFont(fontCustoms.getPoppinsMedium().deriveFont(10f)
        );
        akunEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        akunEmail.setToolTipText("your email based on our database while you register");
        akunEmail.setBorder(null);
        akunEmail.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        akunEmail.setEnabled(false);
        akunEmail.setFocusable(false);
        akunEmail.setNextFocusableComponent(emailTxt);
        akunEmail.setOpaque(false);
        akunEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                akunEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                akunEmailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                akunEmailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                akunEmailMouseReleased(evt);
            }
        });
        panelAkunEmail.add(akunEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));
        akunEmail.getAccessibleContext().setAccessibleName("Type your Full name here");

        bgUsernameRegist.setBackground(new java.awt.Color(255, 255, 255));
        bgUsernameRegist.setBorder(null);
        bgUsernameRegist.setEnabled(false);
        bgUsernameRegist.setTepi(25);
        bgUsernameRegist.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgUsernameRegist.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgUsernameRegist.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelAkunEmail.add(bgUsernameRegist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelAkunEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 300, 150));

        panelEmail.setOpaque(false);
        panelEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel7.setText("Email");
        panelEmail.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        emailTxt.setFont(fontCustoms.getPoppinsMedium().deriveFont(18f)
        );
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTxt.setText("Type your email here");
        emailTxt.setToolTipText("Type your email here and hit enter to active Verify Btn");
        emailTxt.setBorder(null);
        emailTxt.setEnabled(false);
        emailTxt.setFocusable(false);
        emailTxt.setNextFocusableComponent(passwordReg);
        emailTxt.setOpaque(false);
        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFocusGained(evt);
            }
        });
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailTxtMouseReleased(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        panelEmail.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgEmail.setBackground(new java.awt.Color(255, 255, 255));
        bgEmail.setBorder(null);
        bgEmail.setEnabled(false);
        bgEmail.setTepi(25);
        bgEmail.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgEmail.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgEmail.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelEmail.add(bgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 300, 150));

        panelPasswordReg.setOpaque(false);
        panelPasswordReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel8.setText("Password");
        panelPasswordReg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        passwordReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordReg.setText("password");
        passwordReg.setToolTipText("password");
        passwordReg.setBorder(null);
        passwordReg.setEchoChar('\u0000');
        passwordReg.setEnabled(false);
        passwordReg.setFocusable(false);
        passwordReg.setNextFocusableComponent(passwordConfirm);
        passwordReg.setOpaque(false);
        passwordReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegFocusGained(evt);
            }
        });
        passwordReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordRegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordRegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordRegMouseReleased(evt);
            }
        });
        panelPasswordReg.add(passwordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgPassword.setBackground(new java.awt.Color(255, 255, 255));
        bgPassword.setBorder(null);
        bgPassword.setEnabled(false);
        bgPassword.setTepi(25);
        bgPassword.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgPassword.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgPassword.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelPasswordReg.add(bgPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelPasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 300, 150));

        panelPasswordConfirm.setOpaque(false);
        panelPasswordConfirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(20f)
        );
        jLabel9.setText("Confirmation Password");
        panelPasswordConfirm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        passwordConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordConfirm.setText("password");
        passwordConfirm.setToolTipText("password");
        passwordConfirm.setBorder(null);
        passwordConfirm.setEchoChar('\u0000');
        passwordConfirm.setEnabled(false);
        passwordConfirm.setFocusable(false);
        passwordConfirm.setNextFocusableComponent(ceklis);
        passwordConfirm.setOpaque(false);
        passwordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordConfirmFocusGained(evt);
            }
        });
        passwordConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordConfirmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordConfirmMouseReleased(evt);
            }
        });
        passwordConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordConfirmKeyReleased(evt);
            }
        });
        panelPasswordConfirm.add(passwordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        bgPasswordConfirm.setBackground(new java.awt.Color(255, 255, 255));
        bgPasswordConfirm.setBorder(null);
        bgPasswordConfirm.setEnabled(false);
        bgPasswordConfirm.setTepi(25);
        bgPasswordConfirm.setWarnaClick(new java.awt.Color(255, 255, 0));
        bgPasswordConfirm.setWarnaOver(new java.awt.Color(255, 153, 51));
        bgPasswordConfirm.setWarnaTepi(new java.awt.Color(255, 153, 51));
        panelPasswordConfirm.add(bgPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 50));

        panelRegisterForm.add(panelPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 300, 150));

        readPrivasi.setFont(fontCustoms.getPoppinsSemiBold().deriveFont(12f)
        );
        readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
        readPrivasi.setText("read Privacy and Policy");
        readPrivasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                readPrivasiFocusGained(evt);
            }
        });
        readPrivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readPrivasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readPrivasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readPrivasiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                readPrivasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                readPrivasiMouseReleased(evt);
            }
        });
        readPrivasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readPrivasiKeyPressed(evt);
            }
        });
        panelRegisterForm.add(readPrivasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));
        panelRegisterForm.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 240, 10));

        ceklis.setText("I accept Privacy and Policy");
        ceklis.setEnabled(false);
        ceklis.setNextFocusableComponent(changePasswordBtn);
        ceklis.setOpaque(false);
        ceklis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ceklisItemStateChanged(evt);
            }
        });
        ceklis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ceklisKeyPressed(evt);
            }
        });
        panelRegisterForm.add(ceklis, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        verifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        verifyBtn.setBorder(null);
        verifyBtn.setText("Verify");
        verifyBtn.setEnabled(false);
        verifyBtn.setFont(fontCustoms.getRobotoBlak().deriveFont(14f)
        );
        verifyBtn.setTepi(25);
        verifyBtn.setWarnaClick(new java.awt.Color(255, 255, 0));
        verifyBtn.setWarnaOver(new java.awt.Color(255, 153, 51));
        verifyBtn.setWarnaTepi(new java.awt.Color(255, 153, 51));
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });
        verifyBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verifyBtnKeyPressed(evt);
            }
        });
        panelRegisterForm.add(verifyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 80, 50));

        cariBtn.setBackground(new java.awt.Color(255, 255, 255));
        cariBtn.setBorder(null);
        cariBtn.setText("Search");
        cariBtn.setEnabled(false);
        cariBtn.setFont(fontCustoms.getRobotoBlak().deriveFont(14f)
        );
        cariBtn.setTepi(25);
        cariBtn.setWarnaClick(new java.awt.Color(255, 255, 0));
        cariBtn.setWarnaOver(new java.awt.Color(255, 153, 51));
        cariBtn.setWarnaTepi(new java.awt.Color(255, 153, 51));
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });
        cariBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariBtnKeyPressed(evt);
            }
        });
        panelRegisterForm.add(cariBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 80, 50));

        changePasswordBtn.setBackground(new java.awt.Color(255, 255, 255));
        changePasswordBtn.setBorder(null);
        changePasswordBtn.setText("Change your Password");
        changePasswordBtn.setEnabled(false);
        changePasswordBtn.setFont(fontCustoms.getRobotoBlak().deriveFont(14f)
        );
        changePasswordBtn.setTepi(25);
        changePasswordBtn.setWarnaClick(new java.awt.Color(255, 255, 0));
        changePasswordBtn.setWarnaOver(new java.awt.Color(255, 153, 51));
        changePasswordBtn.setWarnaTepi(new java.awt.Color(255, 153, 51));
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });
        panelRegisterForm.add(changePasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 200, 50));

        bgWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/whiteopc50.png"))); // NOI18N
        panelRegisterForm.add(bgWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panelBg.add(panelRegisterForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BackgroundWellcome1.png"))); // NOI18N
        panelBg.add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);
        menuBar.setFont(fontCustoms.getRobotoMedium().deriveFont(20f)
        );
        menuBar.setMaximumSize(new java.awt.Dimension(1020, 50));
        menuBar.setOpaque(false);
        menuBar.setPreferredSize(new java.awt.Dimension(1020, 30));

        menuFile.setBorder(null);
        menuFile.setText("File");
        menuFile.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        startMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        startMenu.setText("Start");
        startMenu.setBorder(null);
        startMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMenuActionPerformed(evt);
            }
        });
        menuFile.add(startMenu);

        loginMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        loginMenu.setText("Login");
        loginMenu.setBorder(null);
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        menuFile.add(loginMenu);

        menuBar.add(menuFile);

        menuHelp.setBorder(null);
        menuHelp.setText("Help");
        menuHelp.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
        );

        helpMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        helpMenu.setText("Help");
        helpMenu.setBorder(null);
        menuHelp.add(helpMenu);

        aboutMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
        aboutMenu.setText("About");
        aboutMenu.setBorder(null);
        menuHelp.add(aboutMenu);

        menuBar.add(menuHelp);

        menutTitle.setText(getTitle());
        menutTitle.setContentAreaFilled(false);
        menutTitle.setEnabled(false);
        menutTitle.setFont(fontCustoms.getRobotoMedium().deriveFont(14f));
        menutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menutTitle.setIconTextGap(400);
        menutTitle.setMaximumSize(new java.awt.Dimension(1000, 50));
        menutTitle.setPreferredSize(new java.awt.Dimension(880, 24));
        menutTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menutTitleMouseDragged(evt);
            }
        });
        menutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menutTitleMousePressed(evt);
            }
        });
        menuBar.add(menutTitle);

        XBtn.setBorder(null);
        XBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/button-x.png"))); // NOI18N
        XBtn.setContentAreaFilled(false);
        XBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        XBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });
        menuBar.add(XBtn);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBtnMouseClicked

    private void menutTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMousePressed
        // TODO add your handling code here:
        lokasi.pressed(evt);
    }//GEN-LAST:event_menutTitleMousePressed

    private void menutTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMouseDragged
        // TODO add your handling code here:
        lokasi.dragged(evt);
    }//GEN-LAST:event_menutTitleMouseDragged

    private void startMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMenuActionPerformed
        // TODO add your handling code here:
        WelcomeFrameStart start = new WelcomeFrameStart();
        start.setLocation(lokasi.p());
        start.setVisible(true);
        dispose();
    }//GEN-LAST:event_startMenuActionPerformed

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
        login.setLocation(lokasi.p());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginMenuActionPerformed

    private void namaAkunTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaAkunTxtMouseEntered
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarnaOver());
        this.over = true;
        namaAkunTxt.setFocusable(over);
    }//GEN-LAST:event_namaAkunTxtMouseEntered

    private void namaAkunTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaAkunTxtMouseExited
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarna());
        this.over = false;
    }//GEN-LAST:event_namaAkunTxtMouseExited

    private void namaAkunTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaAkunTxtMousePressed
        // TODO add your handling code here:
        bgfullname.setBackground(bgfullname.getWarnaClick());
        namaAkunTxt.selectAll();
    }//GEN-LAST:event_namaAkunTxtMousePressed

    private void namaAkunTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaAkunTxtMouseReleased
        // TODO add your handling code here:
        if(this.over) {
            bgfullname.setBackground(bgfullname.getWarnaOver());
        } else {
            bgfullname.setBackground(bgfullname.getWarna());
        }
    }//GEN-LAST:event_namaAkunTxtMouseReleased

    private void akunEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunEmailMouseEntered
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaOver());
        this.over = true;
        akunEmail.setFocusable(over);
    }//GEN-LAST:event_akunEmailMouseEntered

    private void akunEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunEmailMouseExited
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarna());
        this.over = false;
    }//GEN-LAST:event_akunEmailMouseExited

    private void akunEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunEmailMousePressed
        // TODO add your handling code here:
        bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaClick());
        akunEmail.selectAll();
    }//GEN-LAST:event_akunEmailMousePressed

    private void akunEmailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunEmailMouseReleased
        // TODO add your handling code here:
        if (this.over) {
            bgUsernameRegist.setBackground(bgUsernameRegist.getWarnaOver());
        } else {
            bgUsernameRegist.setBackground(bgUsernameRegist.getWarna());
        }
    }//GEN-LAST:event_akunEmailMouseReleased

    private void readPrivasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseEntered
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.over = true;
        readPrivasi.setOpaque(over);
//        readPrivasi.setBackground(Color.WHITE);
    }//GEN-LAST:event_readPrivasiMouseEntered

    private void readPrivasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseExited
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.over = false;
        readPrivasi.setOpaque(over);
    }//GEN-LAST:event_readPrivasiMouseExited

    private void readPrivasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMousePressed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readPrivasi.setForeground(Color.WHITE);
        readPrivasi.setOpaque(true);
        
    }//GEN-LAST:event_readPrivasiMousePressed

    private void readPrivasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseReleased
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        if(this.over) {
            readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
            readPrivasi.setOpaque(false);
        } else {
            readPrivasi.setForeground(new java.awt.Color(0, 0, 204));
            readPrivasi.setOpaque(false);
        }
    }//GEN-LAST:event_readPrivasiMouseReleased

    private void passwordRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseEntered
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarnaOver());
        this.over = true;
        passwordReg.setFocusable(over);
    }//GEN-LAST:event_passwordRegMouseEntered

    private void passwordRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseExited
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarna());
        this.over = true;
    }//GEN-LAST:event_passwordRegMouseExited

    private void passwordRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMousePressed
        // TODO add your handling code here:
        bgPassword.setBackground(bgPassword.getWarnaClick());
        passwordReg.setEchoChar('\u25cf');
    }//GEN-LAST:event_passwordRegMousePressed

    private void passwordRegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordRegMouseReleased
        // TODO add your handling code here:
        if(this.over){
            bgPassword.setBackground(bgPassword.getWarnaOver());
        } else {
            bgPassword.setBackground(bgPassword.getWarna());
        }
    }//GEN-LAST:event_passwordRegMouseReleased

    private void passwordConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseEntered
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaOver());
        this.over = true;
        passwordConfirm.setFocusable(over);
    }//GEN-LAST:event_passwordConfirmMouseEntered

    private void passwordConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseExited
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarna());
        this.over = false;
    }//GEN-LAST:event_passwordConfirmMouseExited

    private void passwordConfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMousePressed
        // TODO add your handling code here:
        bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaClick());
        passwordConfirm.setEchoChar('\u25cf');
    }//GEN-LAST:event_passwordConfirmMousePressed

    private void passwordConfirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordConfirmMouseReleased
        // TODO add your handling code here:
        if (this.over){
            bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarnaOver());
        } else {
            bgPasswordConfirm.setBackground(bgPasswordConfirm.getWarna());
        }
    }//GEN-LAST:event_passwordConfirmMouseReleased

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Tombol register clicked");
        forgotPasswordModel = new ForgotPasswordModel(
                namaAkunTxt.getText(),
                emailTxt.getText(),
                passwordReg.getText(),
                passwordConfirm.getText()
        );
        forgotPasswordController = new ForgotPasswordController(this, forgotPasswordModel);
//        System.out.println(forgotPasswordController.btnChange());
        if (forgotPasswordController.btnChange()) {
            login.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void ceklisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ceklisItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePasswordBtn.setEnabled(true);
        } else {
            changePasswordBtn.setEnabled(false);
        }
    }//GEN-LAST:event_ceklisItemStateChanged

    private void namaAkunTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaAkunTxtFocusGained
        // TODO add your handling code here:
        if (namaAkunTxt.getText().equals("Type your username")) {
            namaAkunTxt.setText("");
            akunEmail.setFocusable(true);
        } else if (namaAkunTxt.hasFocus()) {
            namaAkunTxt.selectAll();
        }
    }//GEN-LAST:event_namaAkunTxtFocusGained

    private void passwordRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegFocusGained
        // TODO add your handling code here:
        if (passwordReg.getText().equals("password")) {
            passwordReg.setText("");
            passwordConfirm.setFocusable(true);
            passwordReg.setEchoChar('\u25cf');
        } else if (passwordReg.hasFocus()) {
            passwordReg.selectAll();
        }
    }//GEN-LAST:event_passwordRegFocusGained

    private void passwordConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordConfirmFocusGained
        // TODO add your handling code here:
        if (passwordConfirm.getText().equals("password")) {
            passwordConfirm.setText("");
            ceklis.setEnabled(true);
            passwordConfirm.setEchoChar('\u25cf');
        } else if (passwordConfirm.hasFocus()) {
            passwordConfirm.selectAll();
        }
    }//GEN-LAST:event_passwordConfirmFocusGained

    private void emailTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusGained
        // TODO add your handling code here:
        if (emailTxt.getText().equals("Type your email here")) {
            emailTxt.setText("");
            passwordReg.setFocusable(true);
        } else if (emailTxt.hasFocus()) {
            emailTxt.selectAll();
        }
    }//GEN-LAST:event_emailTxtFocusGained

    private void emailTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseEntered
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarnaOver());
        this.over = true;
        emailTxt.setFocusable(over);
    }//GEN-LAST:event_emailTxtMouseEntered

    private void emailTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseExited
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarna());
        this.over = true;
    }//GEN-LAST:event_emailTxtMouseExited

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMousePressed
        // TODO add your handling code here:
        bgEmail.setBackground(bgEmail.getWarnaClick());
    }//GEN-LAST:event_emailTxtMousePressed

    private void emailTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseReleased
        // TODO add your handling code here:
        if (this.over) {
            bgEmail.setBackground(bgEmail.getWarnaOver());
        } else {
            bgEmail.setBackground(bgEmail.getWarna());
        }
    }//GEN-LAST:event_emailTxtMouseReleased

    private void ceklisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ceklisKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == false) {
            ceklis.setSelected(true);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == true) {
            ceklis.setSelected(false);
        }
    }//GEN-LAST:event_ceklisKeyPressed

    private void passwordConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordConfirmKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == false) {
            int confirmDialog;
            confirmDialog = JOptionPane.showConfirmDialog(null, "Please Accept our Privacy and Policy!"+"\n"+
                    "Click Cancek to read our Privacy and Policy!","EROR",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if ( confirmDialog == JOptionPane.CANCEL_OPTION) {
                passwordConfirm.setNextFocusableComponent(readPrivasi);
                passwordConfirm.nextFocus();
            } else if (confirmDialog == JOptionPane.OK_OPTION) {
                passwordConfirm.setNextFocusableComponent(ceklis);
                passwordConfirm.nextFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && ceklis.isSelected() == true) {
            changePasswordBtn.doClick();
        }
    }//GEN-LAST:event_passwordConfirmKeyReleased

    private void readPrivasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readPrivasiMouseClicked
        // TODO add your handling code here:
        System.out.println("read it");
    }//GEN-LAST:event_readPrivasiMouseClicked

    private void readPrivasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readPrivasiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("read it");
        }
    }//GEN-LAST:event_readPrivasiKeyPressed

    private void readPrivasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_readPrivasiFocusGained
        // TODO add your handling code here:
        if (readPrivasi.hasFocus()) {
            readPrivasi.setOpaque(true);
            readPrivasi.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_readPrivasiFocusGained

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        // TODO add your handling code here:
       forgotPasswordModel = new ForgotPasswordModel(namaAkunTxt.getText());
       forgotPasswordController = new ForgotPasswordController(this, forgotPasswordModel);
       forgotPasswordController.btnCari();
       
//        String akun = namaAkunTxt.getText();
        String output = forgotPasswordController.getOutputDisplay();
        akunEmail.setText(output);
        emailTxt.setEnabled(true);
        
    }//GEN-LAST:event_cariBtnActionPerformed

    private void namaAkunTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaAkunTxtActionPerformed
        // TODO add your handling code here:
        cariBtn.setEnabled(!namaAkunTxt.getText().isEmpty());
    }//GEN-LAST:event_namaAkunTxtActionPerformed

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        // TODO add your handling code here:
        
        forgotPasswordModel = new ForgotPasswordModel(
                namaAkunTxt.getText(),
                emailTxt.getText());
        
        forgotPasswordController = new ForgotPasswordController(this, forgotPasswordModel);
        if (forgotPasswordController.btnVerify()) {
            
//        }
//        String ke1, ke2;
//        ke1 = namaAkunTxt.getText();
//        ke2 = emailTxt.getText();
//        
//        if (ke1.equals(ke2)) {
            passwordReg.setEnabled(true);
            passwordConfirm.setEnabled(true);
//            ceklis.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "not match in database!","eror",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
        verifyBtn.setEnabled(!emailTxt.getText().isEmpty());
    }//GEN-LAST:event_emailTxtActionPerformed

    private void cariBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariBtnKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cariBtn.doClick();
        }
    }//GEN-LAST:event_cariBtnKeyPressed

    private void verifyBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifyBtnKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verifyBtn.doClick();
        }
    }//GEN-LAST:event_verifyBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrameForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JMenu XBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JTextField akunEmail;
    private crud_apps.Controller.CustomButton bgEmail;
    private crud_apps.Controller.CustomButton bgPassword;
    private crud_apps.Controller.CustomButton bgPasswordConfirm;
    private crud_apps.Controller.CustomButton bgUsernameRegist;
    private javax.swing.JLabel bgWhite;
    private crud_apps.Controller.CustomButton bgfullname;
    private crud_apps.Controller.CustomButton cariBtn;
    private javax.swing.JCheckBox ceklis;
    private crud_apps.Controller.CustomButton changePasswordBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menutTitle;
    private javax.swing.JTextField namaAkunTxt;
    private javax.swing.JPanel panelAkunEmail;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelPasswordConfirm;
    private javax.swing.JPanel panelPasswordReg;
    private javax.swing.JPanel panelRegisterForm;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPasswordField passwordConfirm;
    private javax.swing.JPasswordField passwordReg;
    private javax.swing.JLabel readPrivasi;
    private javax.swing.JMenuItem startMenu;
    private crud_apps.Controller.CustomButton verifyBtn;
    // End of variables declaration//GEN-END:variables

    public JPasswordField getPasswordConfirm() {
        return passwordConfirm;
    }

    public JPasswordField getPasswordReg() {
        return passwordReg;
    }

}