/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_apps.View.Welcome;

import crud_apps.Controller.CustomButton;
import crud_apps.Controller.CustomFonts;
import crud_apps.Controller.Lokasi;

/**
 *
 * @author Wahyu Khoirur Rizal
 */
public class WelcomeFrameStart extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    Lokasi lokasi = new Lokasi(this);
    CustomFonts fontCustoms = new CustomFonts();
    public WelcomeFrameStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        StartBtn = new crud_apps.Controller.CustomButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bgWhite = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        registerMenu = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        menutTitle = new javax.swing.JMenu();
        XBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1020, 670));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setBackground(new java.awt.Color(255, 255, 255));
        panelBg.setMinimumSize(new java.awt.Dimension(1020, 670));
        panelBg.setPreferredSize(new java.awt.Dimension(1020, 670));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StartBtn.setBackground(new java.awt.Color(0, 204, 204));
        StartBtn.setBorder(null);
        StartBtn.setForeground(new java.awt.Color(255, 255, 255));
        StartBtn.setText("Start");
        StartBtn.setFocusPainted(false);
        StartBtn.setFocusTraversalPolicyProvider(true);
        StartBtn.setFont(fontCustoms.getStarjedise().deriveFont(18f)
        );
        StartBtn.setTepi(45);
        StartBtn.setWarna(new java.awt.Color(0, 204, 204));
        StartBtn.setWarnaClick(new java.awt.Color(204, 255, 255));
        StartBtn.setWarnaOver(new java.awt.Color(0, 102, 255));
        StartBtn.setWarnaTepi(new java.awt.Color(0, 0, 102));
        StartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StartBtnMouseReleased(evt);
            }
        });
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 130, 50));

        jLabel3.setFont(fontCustoms.getRubikMedium().deriveFont(14f)
        );
        jLabel3.setText("to begin your journey !");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel1.setFont(fontCustoms.getStarjedise().deriveFont(24f)
        );
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Start");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel4.setFont(fontCustoms.getHandleeRegular().deriveFont(20f)
        );
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("click");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel5.setFont(fontCustoms.getRubikMedium().deriveFont(14f)
        );
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("on below");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        bgWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BgWhite.png"))); // NOI18N
        bgWhite.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 4, true), "Welcome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, fontCustoms.getRobotoMedium().deriveFont(18f)
            , new java.awt.Color(204, 255, 255)));
    jPanel1.add(bgWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

    panelBg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

    BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/BackgroundWellcome1.png"))); // NOI18N
    panelBg.add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 670));

    menuBar.setBackground(new java.awt.Color(255, 255, 255));
    menuBar.setBorder(null);
    menuBar.setBorderPainted(false);
    menuBar.setFont(fontCustoms.getRobotoMedium().deriveFont(20f)
    );
    menuBar.setMaximumSize(new java.awt.Dimension(1020, 50));
    menuBar.setOpaque(false);
    menuBar.setPreferredSize(new java.awt.Dimension(1020, 30));

    menuFile.setBorder(null);
    menuFile.setText("File");
    menuFile.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
    );

    loginMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
    loginMenu.setText("Login");
    loginMenu.setBorder(null);
    loginMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginMenuActionPerformed(evt);
        }
    });
    menuFile.add(loginMenu);

    registerMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
    registerMenu.setText("Register");
    registerMenu.setBorder(null);
    registerMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registerMenuActionPerformed(evt);
        }
    });
    menuFile.add(registerMenu);

    menuBar.add(menuFile);

    menuHelp.setBorder(null);
    menuHelp.setText("Help");
    menuHelp.setFont(fontCustoms.getRobotoMedium().deriveFont(16f)
    );

    helpMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
    helpMenu.setText("Help");
    helpMenu.setBorder(null);
    menuHelp.add(helpMenu);

    aboutMenu.setFont(fontCustoms.getRobotoMedium().deriveFont(16f));
    aboutMenu.setText("About");
    aboutMenu.setBorder(null);
    menuHelp.add(aboutMenu);

    menuBar.add(menuHelp);

    menutTitle.setText(getTitle());
    menutTitle.setContentAreaFilled(false);
    menutTitle.setEnabled(false);
    menutTitle.setFont(fontCustoms.getRobotoMedium().deriveFont(14f));
    menutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    menutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    menutTitle.setIconTextGap(400);
    menutTitle.setMaximumSize(new java.awt.Dimension(1000, 50));
    menutTitle.setPreferredSize(new java.awt.Dimension(880, 24));
    menutTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            menutTitleMouseDragged(evt);
        }
    });
    menutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            menutTitleMousePressed(evt);
        }
    });
    menuBar.add(menutTitle);

    XBtn.setBorder(null);
    XBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_apps/Model/img/button-x.png"))); // NOI18N
    XBtn.setContentAreaFilled(false);
    XBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    XBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            XBtnMouseClicked(evt);
        }
    });
    menuBar.add(XBtn);

    setJMenuBar(menuBar);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBtnMouseClicked

    private void StartBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseEntered
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_StartBtnMouseEntered

    private void StartBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseExited
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_StartBtnMouseExited

    private void StartBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMousePressed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_StartBtnMousePressed

    private void StartBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseReleased
        // TODO add your handling code here:
        CustomButton getOver = new CustomButton();
        if (getOver.isOver()) {
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        } else {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_StartBtnMouseReleased

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        // TODO add your handling code here:'
        WelcomeFrameLogin login = new WelcomeFrameLogin();
        login.setLocation(lokasi.p());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_StartBtnActionPerformed

    private void menutTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMousePressed
        // TODO add your handling code here:
        lokasi.pressed(evt);
    }//GEN-LAST:event_menutTitleMousePressed

    private void menutTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutTitleMouseDragged
         // TODO add your handling code here:
        lokasi.dragged(evt);
    }//GEN-LAST:event_menutTitleMouseDragged

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
        WelcomeFrameLogin login = new WelcomeFrameLogin();
        login.setLocation(lokasi.p());
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginMenuActionPerformed

    private void registerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuActionPerformed
        // TODO add your handling code here:
        WelcomeFrameRegister register = new WelcomeFrameRegister();
        register.setLocation(lokasi.p());
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrameStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private crud_apps.Controller.CustomButton StartBtn;
    private javax.swing.JMenu XBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JLabel bgWhite;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menutTitle;
    private javax.swing.JPanel panelBg;
    private javax.swing.JMenuItem registerMenu;
    // End of variables declaration//GEN-END:variables
}
